# pyproject.toml
target-version = "py311"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.ruff]
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 88

[flake8]
max-line-length=88
